<?php

namespace biero\visiteurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsagerRepository extends EntityRepository
{
}
